### ISSUE TITLE
Publish SDK packages to NuGet

### ISSUE THREAD

**Issue by Qonfused** [videre-project/MTGOSDK#12]
The current SDK is only set up for users to build against a clone of the project. This is mostly due to unresolved questions on how/whether to distribute reference assemblies generated by the **MTGOSDK.Ref** project, which are required runtime dependencies by the main MTGOSDK library (for reflection).

Only the **MTGOSDK** and **MTGOSDK.Win32** libraries would need to be published to NuGet, requiring an additional pipeline for packaging the built reference assemblies.

This also requires additional infrastructure for supporting publishing and building the SDK through .NET Core.

```[tasklist]
### Tasks
- [ ] https://github.com/videre-project/MTGOSDK/pull/8
- [ ] https://github.com/videre-project/MTGOSDK/pull/9
- [ ] https://github.com/videre-project/MTGOSDK/pull/13
- [ ] https://github.com/videre-project/MTGOSDK/pull/14
- [ ] https://github.com/videre-project/MTGOSDK/issues/16
- [ ] https://github.com/videre-project/MTGOSDK/issues/15
- [ ] https://github.com/videre-project/MTGOSDK/pull/20
- [ ] https://github.com/videre-project/MTGOSDK/pull/22
- [ ] https://github.com/videre-project/MTGOSDK/pull/23
- [x] Create NuGet publish pipeline for MTGOSDK
- [ ] https://github.com/videre-project/MTGOSDK/issues/19
- [ ] Hook publishing to GitHub Actions CI
```

**Comment by Qonfused** [comment]
Within the **MTGOSDK.Ref** project, a new target should include the built reference assemblies for consumption *through* the library (without needing explicit references for each DLL):
```xml
<!-- Packaging assemblies for NuGet publishing -->
<ItemGroup>
  <Content Include="$(_MTGOSDK_Refs)\*.dll">
    <Pack>true</Pack>
    <PackagePath>lib\$(TargetFramework)</PackagePath>
  </Content>
</ItemGroup>
```
```xml
<!-- Importing MTGOSDK.Ref in a consuming project -->
<PackageReference Include="VidereProject.MTGOSDK.Ref"
                  Version="1.0.0" />
```

Versus the current setup, which requires bootstrapping the **MTGOSDK.Ref** project with **MTGOSDK.MSBuild**:
```xml
<!--
  Bootstrap the MTGOSDK.Ref project to generate reference assemblies for
  the current MTGO version. Due to the way that MSBuild works, this must
  import the MTGOSDK.MSBuild.props file before referencing the project.
-->
<Import Project="..\MTGOSDK.MSBuild\build\MTGOSDK.MSBuild.props" />
<PropertyGroup>
  <MTGOSDK_Refs>$(_MTGOSDK_Refs)\3.4.*.*</MTGOSDK_Refs>
</PropertyGroup>
<ItemGroup>
  <ProjectReference Include="..\MTGOSDK.Ref\MTGOSDK.Ref.csproj"
                    ReferenceOutputAssembly="false" />
  <!--
    Include reference assemblies to compile against the current MTGO version.
    Note that the '_MTGOSDK_Refs' path does not reference the updated version
    subpath as it is only evaluated after building the MTGOSDK.Ref project.
  -->
  <Reference Include="$(MTGOSDK_Refs)\Core.dll" />
  <Reference Include="$(MTGOSDK_Refs)\FlsClient.dll" />
  <Reference Include="$(MTGOSDK_Refs)\MTGOEnumStruct.dll" />
  <Reference Include="$(MTGOSDK_Refs)\WotC.MtGO.Client.Common.dll" />
  <Reference Include="$(MTGOSDK_Refs)\WotC.MtGO.Client.Model.Chat.dll" />
  <Reference Include="$(MTGOSDK_Refs)\WotC.MtGO.Client.Model.Core.dll" />
  <Reference Include="$(MTGOSDK_Refs)\WotC.MtGO.Client.Model.Reference.dll" />
</ItemGroup>
```

**Comment by Qonfused** [comment]
Should look into packaging properties/targets under a `buildTransitive` folder in the NuGet package ([reference](https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior)).

Bootstrapping MTGO reference assembly generation at project reference and evaluating includes dynamically would avoid needing to publish the reference assemblies themselves.

Below is an example of how this can be used in the MTGOSDK library (as well as in consumer applications):
```xml
<ItemGroup>
  <!--
    Import the MTGOSDK.Ref project to generate reference assemblies for the
    current MTGO version. Consumers of MTGOSDK should not need to reference
    this project directly as it is imported transitively.
  -->
  <ProjectReference Include="..\MTGOSDK.Ref\MTGOSDK.Ref.csproj"
                    ReferenceOutputAssembly="false" />
  <!--
    Include reference assemblies to compile against the current MTGO version.
  -->
  <ReferenceAssembly Include="Core.dll" />
  <ReferenceAssembly Include="FlsClient.dll" />
  <ReferenceAssembly Include="MTGOEnumStruct.dll" />
  <ReferenceAssembly Include="WotC.MtGO.Client.Common.dll" />
  <ReferenceAssembly Include="WotC.MtGO.Client.Model.Chat.dll" />
  <ReferenceAssembly Include="WotC.MtGO.Client.Model.Core.dll" />
  <ReferenceAssembly Include="WotC.MtGO.Client.Model.Reference.dll" />
</ItemGroup>
```

**Comment by Qonfused** [comment]
Following #16, reference assemblies are still bundled with the MTGOSDK project.

Unfortunately, there isn't a reliable way of conditionally including them based on the consuming project; specifying properties doesn't work transitively or for project references (MSBuild regression).

For now, this is exposed through a `UseRef` property:
https://github.com/videre-project/MTGOSDK/blob/cad97367f687b60d59915e144b522c4844ba2a78/MTGOSDK/MTGOSDK.ref.props#L9-L41

**Comment by Qonfused** [comment]
Reference assemblies are now merged with the MTGOSDK library and are not distributed separately (resolved in 4b26663f425c426edfb4d8fc1a1bc4cc5b5b3c63). Transitive build targets are still bundled with MTGOSDK through MTGOSDK.MSBuild.

**Comment by Qonfused** [comment]
Ported SharpNeedle to use [MSVCToolchain](https://github.com/Qonfused/MSVCToolchain) in https://github.com/videre-project/MTGOSDK/commit/2a632c395781c8f0d79c49e003863113c95f73d6. Will revert if or when VS C++ project tooling is supported by the .NET (Core) CLI.
