### ISSUE TITLE
Migrate HTTP clients to gRPC

### ISSUE THREAD

**Issue by Qonfused** [videre-project/MTGOSDK#4]
Using gRPC should allow for better interop between languages and the host/client processes with support for bidirectional streaming, flow control, and comparatively better error handling. This will upgrade communication to HTTP/2 and require additional codegen for supporting protocol buffers. 

Microsoft has a tutorial [here](https://learn.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-7.0) explaining how to support this with existing C#/MSBuild projects, though this may be a better migration path for #2.
```[tasklist]
### Tasks
- [ ] https://github.com/videre-project/MTGOSDK/pull/14
- [ ] https://github.com/videre-project/MTGOSDK/issues/11
- [ ] https://github.com/videre-project/MTGOSDK/pull/22
- [ ] https://github.com/videre-project/MTGOSDK/pull/23
- [ ] Rewrite ScubaDiver API as gRPC services
```

**Comment by Qonfused** [comment]
Some alternatives include [Apache Avro](https://avro.apache.org/docs/current/) which may be better suited for developer familiarity with JSON and human-readable schemas if a high-throughput/low-latency protocol w/ protobufs isn't very impactful.

**Comment by Qonfused** [comment]
Superceded by #37.
